// <auto-generated />
using System;
using DevsuApp.BE.Infraestructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DevsuApp.BE.Infraestructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251027012050_InitialEntities")]
    partial class InitialEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DevsuApp.BE.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteId"));

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ClienteId");

                    b.HasIndex("Identificacion")
                        .IsUnique()
                        .HasDatabaseName("IX_Clientes_Identificacion_Unique");

                    b.ToTable("Clientes", (string)null);

                    b.HasData(
                        new
                        {
                            ClienteId = 1,
                            Contrasena = "1234",
                            Direccion = "Otavalo sn y principal",
                            Edad = 35,
                            Estado = true,
                            Genero = "Masculino",
                            Identificacion = "1234567890",
                            Nombre = "Jose Lema",
                            PersonaId = 0,
                            Telefono = "0982547851"
                        },
                        new
                        {
                            ClienteId = 2,
                            Contrasena = "5678",
                            Direccion = "Amazonas y NNUU",
                            Edad = 28,
                            Estado = true,
                            Genero = "Femenino",
                            Identificacion = "0987654321",
                            Nombre = "Marianela Montalvo",
                            PersonaId = 0,
                            Telefono = "0975489655"
                        },
                        new
                        {
                            ClienteId = 3,
                            Contrasena = "1245",
                            Direccion = "13 junio y Equinoccial",
                            Edad = 42,
                            Estado = true,
                            Genero = "Masculino",
                            Identificacion = "1122334455",
                            Nombre = "Juan Osorio",
                            PersonaId = 0,
                            Telefono = "0988745871"
                        });
                });

            modelBuilder.Entity("DevsuApp.BE.Domain.Entities.Cuenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("NumeroCuenta")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("SaldoInicial")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TipoCuenta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("NumeroCuenta")
                        .IsUnique()
                        .HasDatabaseName("IX_Cuentas_NumeroCuenta_Unique");

                    b.ToTable("Cuentas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClienteId = 1,
                            Estado = true,
                            NumeroCuenta = "478758",
                            SaldoInicial = 2000m,
                            TipoCuenta = "Ahorro"
                        },
                        new
                        {
                            Id = 2,
                            ClienteId = 2,
                            Estado = true,
                            NumeroCuenta = "225487",
                            SaldoInicial = 100m,
                            TipoCuenta = "Corriente"
                        },
                        new
                        {
                            Id = 3,
                            ClienteId = 3,
                            Estado = true,
                            NumeroCuenta = "495878",
                            SaldoInicial = 0m,
                            TipoCuenta = "Ahorro"
                        },
                        new
                        {
                            Id = 4,
                            ClienteId = 2,
                            Estado = true,
                            NumeroCuenta = "496825",
                            SaldoInicial = 540m,
                            TipoCuenta = "Ahorro"
                        });
                });

            modelBuilder.Entity("DevsuApp.BE.Domain.Entities.Movimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CuentaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Fecha")
                        .HasDatabaseName("IX_Movimientos_Fecha");

                    b.HasIndex("CuentaId", "Fecha")
                        .HasDatabaseName("IX_Movimientos_CuentaId_Fecha");

                    b.ToTable("Movimientos");
                });

            modelBuilder.Entity("DevsuApp.BE.Domain.Entities.Cuenta", b =>
                {
                    b.HasOne("DevsuApp.BE.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Cuentas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("DevsuApp.BE.Domain.Entities.Movimiento", b =>
                {
                    b.HasOne("DevsuApp.BE.Domain.Entities.Cuenta", "Cuenta")
                        .WithMany("Movimientos")
                        .HasForeignKey("CuentaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cuenta");
                });

            modelBuilder.Entity("DevsuApp.BE.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Cuentas");
                });

            modelBuilder.Entity("DevsuApp.BE.Domain.Entities.Cuenta", b =>
                {
                    b.Navigation("Movimientos");
                });
#pragma warning restore 612, 618
        }
    }
}
